In [1]:
import numpy as np

> Element-wise addition of 2 numpy arrays

In [2]:
a = np.array([
    [1,2,3],
    [4,5,6]])
b = np.array([
    [10,12,14],
    [9,12,15]])
c = a+b
c

array([[11, 14, 17],
       [13, 17, 21]])

> Multiplying a matrix (numpy array) by a scalar

In [3]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
a*2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

> Identity Matrix

In [6]:
i = np.eye(3) #it creates identity matrix which is also a square matrix.
i

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

> Array re-dimensioning

In [9]:
a = np.array([i for i in range(27)]) #3X3X3 = 27
a = a.reshape((3,3,3))
a

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

> Array datatype conversion

In [23]:
a = np.random.randint(2,5,size=(2,3))
a

array([[3, 2, 2],
       [2, 2, 3]])

In [24]:
a = a.astype('float')
a

array([[3., 2., 2.],
       [2., 2., 3.]])

> Obtaining Boolean Array from Binary Array

In [26]:
a = np.array([[1,0,0,1,0],[1,0,1,0,0]])
a

array([[1, 0, 0, 1, 0],
       [1, 0, 1, 0, 0]])

In [27]:
a = a.astype('bool')
a

array([[ True, False, False,  True, False],
       [ True, False,  True, False, False]])

> Horizontal Stacking of Numpy Arrays

In [28]:
a = np.array([[1,2,3],
               [4,5,6]])

b = np.array([[7,8,9],
               [10,11,12]])
a,b

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [10, 11, 12]]))

In [29]:
c = np.hstack((a,b))
c

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

> Vertically Stacking of Numpy Arrays

In [30]:
c = np.vstack((a,b))
c

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

> Custom Sequence Generation

In [32]:
list_of_numbers = [x for x in range(2,100,4)]

o = np.array(list_of_numbers)
o

array([ 2,  6, 10, 14, 18, 22, 26, 30, 34, 38, 42, 46, 50, 54, 58, 62, 66,
       70, 74, 78, 82, 86, 90, 94, 98])

In [34]:
a = np.arange(2,100,4)
a

array([ 2,  6, 10, 14, 18, 22, 26, 30, 34, 38, 42, 46, 50, 54, 58, 62, 66,
       70, 74, 78, 82, 86, 90, 94, 98])

> Getting the positions (indexes) where elements of 2 numpy arrays match

In [40]:
a = np.array([1,2,3,4,5])
b = np.array([1,3,2,4,5])
a,b

(array([1, 2, 3, 4, 5]), array([1, 3, 2, 4, 5]))

In [42]:
print(np.where(a==b)) #this check exact position if equal then return index value condition(i==j and a[i] == b[j])

(array([0, 3, 4], dtype=int64),)


> Generation of given count of equally spaced numbers within a specified range

In [43]:
n = np.linspace(2,20,4)
n

array([ 2.,  8., 14., 20.])

> Matrix Generation with one particular value

In [44]:
#shortcut way
a = np.full((2,4),4)
a

array([[4, 4, 4, 4],
       [4, 4, 4, 4]])

In [46]:
#long term way
b = np.ones((2,4))
b*=4
b

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [51]:
b = b.astype('int')
b

array([[4, 4, 4, 4],
       [4, 4, 4, 4]])

> Array Generation by repeatition of a small array across each dimension

In [52]:
a = np.array([[1,2,3],[4,5,6]])
c = np.tile(a,5) #repeat each element 5 times.
a,c

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3],
        [4, 5, 6, 4, 5, 6, 4, 5, 6, 4, 5, 6, 4, 5, 6]]))

> Array Generation of random integers within a specified range

In [53]:
np.random.seed(150)
a = np.random.randint(0,10,size=(5,5))
a

array([[4, 9, 0, 2, 4],
       [5, 7, 9, 8, 3],
       [8, 1, 1, 4, 4],
       [1, 1, 9, 3, 7],
       [6, 2, 7, 0, 3]])

> Array Generation of random numbers following normal distribution

In [56]:
a = np.random.normal(1,5,size=(3,3))
b = np.random.normal(size=(3,3))
a,b

(array([[ 4.13195787,  2.81050332,  7.30581725],
        [ 3.98488563, -2.67642016,  3.78675053],
        [-3.67678853,  0.71903314,  5.76561812]]),
 array([[-1.00449335, -0.73715392, -2.03846   ],
        [ 0.26039385,  0.27285493, -0.66437923],
        [ 0.04688872, -1.37920986, -0.04554147]]))

> Matrix Multiplication

In [59]:
a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

b = np.array([[2,3,4],
              [5,6,7],
              [8,9,10]])
a,b,a@b #shortcut for matrix multiplication

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[ 2,  3,  4],
        [ 5,  6,  7],
        [ 8,  9, 10]]),
 array([[ 36,  42,  48],
        [ 81,  96, 111],
        [126, 150, 174]]))

In [60]:
c = np.matmul(a,b)#second way for matrix multiplication
c

array([[ 36,  42,  48],
       [ 81,  96, 111],
       [126, 150, 174]])

In [62]:
d = np.dot(a,b) #third way for matrix multiplication
d

array([[ 36,  42,  48],
       [ 81,  96, 111],
       [126, 150, 174]])

> Matrix Transpose

In [63]:
a = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [64]:
a_transpose = a.T
a_transpose

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [66]:
#another way for transpose
a_transpose2 = np.transpose(a)
a_transpose2

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

> Sine , Cosine ,Tangent of an Angle (in radians)

In [67]:
angles = np.array([3.14, 3.14/2, 6.28])
angles

array([3.14, 1.57, 6.28])

In [68]:
#Sin(0)
sine_of_angles = np.sin(angles)
sine_of_angles

array([ 0.00159265,  0.99999968, -0.0031853 ])

In [69]:
#Cos(0)
cosine_of_angles = np.cos(angles)
cosine_of_angles

array([-9.99998732e-01,  7.96326711e-04,  9.99994927e-01])

In [70]:
#tan(0)
tangent_of_angles = np.tan(angles)
tangent_of_angles

array([-1.59265494e-03,  1.25576559e+03, -3.18531795e-03])

> Generating the array element indexes such that the array elements appear in ascending order

In [77]:
#Note : It sort elements in ascending order but result appear as index list or array  
arr1 = np.array([10,1,5,2,21,13,11,9])
arr2 = np.array([1,5,2,21])
arr3 = np.array([1,5,2,21,-12,61,87])
index1 = np.argsort(arr1)
index2 = np.argsort(arr2)
index3 = np.argsort(arr3)
index1 , index2 , index3

(array([1, 3, 2, 7, 0, 6, 5, 4], dtype=int64),
 array([0, 2, 1, 3], dtype=int64),
 array([4, 0, 2, 1, 3, 5, 6], dtype=int64))

In [78]:
arr1[index1]

array([ 1,  2,  5,  9, 10, 11, 13, 21])

In [79]:
arr2[index2]

array([ 1,  2,  5, 21])

In [80]:
arr3[index3]

array([-12,   1,   2,   5,  21,  61,  87])