# **Python NumPy**

*   Numpy is a python package which stands 

*   for Numerical Python.
This was created in 2005 by Travis Oliphant.
*   Using Numpy we can perform the following functionalities : 


> *    Mathematical and logical calculations on Arrays.
> *    Fourier transforms and routines for shape manipulation.
> *    It has built in functions for linear Algebra and random number generation.
> *    Used for scientific calculations.
> *    It is faster than python list.
> *    it is faster because it is associated with C programming language.

*    Numpy is often called as an alternative for MatLab (a programming platform designed specifically for engineers and scientists for data analysis, Developing algorithms,create models and applications etc).
*    Numpy is used with packages like SciPy(Scientific Python) and MatPlotlib(Plotting library) and this makes it capable to replace MatLab.
*    Types of array in Numpy :   
> *    one Dimensional Array as Vector.
> *    two Dimensional Array as Matrix.
> *    three Dimensional Array as Tensor.









> Note : this is done after installing jupyter notebook in cmd or using anaconda.

## Working with jupyter NoteBook
### Jupyter notebook has two modes : 

1.   Command Mode - Blue Color
2.   Edit Mode - Green Color

### Some Shortcuts to remember :  
1.   To run the program you have written press cntrl+enter
2.   To run the command as well as insert a cell below - shift+Enter
3.   To insert a cell below just press "b".
4.   To delete a cell - press Esc button (to go to command mode as in edit mode you can't delete the cell) and then "d" two times.
### Work with Jupyter Notebook
1.   To mark something as comment we press esc button and then 1 and shift+Enter yo execute.
2.   We can also use HTML tags inside this.
3.   To know all the shortcuts, just go to and click on keyboard Shortcuts.


> <h3>Numpy examples :</h3> 

In [187]:
import numpy as np

In [189]:
a = []
n = int(input("Enter size of 1D array : "))
for i in range(n):
  a.append(int(input("Enter number")))
a = np.array(a)
b = np.array([1,1,1])
a

Enter size of 1D array : 5
Enter number1
Enter number2
Enter number3
Enter number4
Enter number5


array([1, 2, 3, 4, 5])

In [ ]:
c = np.append(a,b)
c

In [ ]:
#size to check array size(total number of elements)
#ndim checking dimension of array
c.size , c.ndim

In [ ]:
c.shape

In [ ]:
#slicing is same as we have done in string or list in core python
c[1:] , c[:c.size-3]

In [ ]:
c[-1] , c[:-1]

In [ ]:
c[5:c.size]

In [ ]:
c[-3:]

In [ ]:
c[-5] , c[5]

In [ ]:
c[0] = 10.0
c

In [ ]:
d = [
     {"name" : 'A'},
     {"name" : 'B'},
     {"name" : 'C'},
     {"name" : 'D'},
     {"name" : 'E'}
]
c.dtype

In [ ]:
d

In [ ]:
d = np.array(d)
d

<h3>Numpy Arrays<h3>

> One Dimensional Array

In [ ]:
a = [1,2,3,4,5]
arr = np.array(a)
arr 

In [ ]:
arr2= np.array([2,0,5,6,4])
arr2

In [ ]:
a

In [ ]:
 b = np.arange(0,10)
 b

In [ ]:
b.ndim

In [ ]:
b.T , b

In [ ]:
np.empty(2)

> 2 Dimensional Array

In [ ]:
c = [[1,2,],[3,4]]
c

In [ ]:
c1 = np.array(c , dtype=float)
c1

In [ ]:
c1.T

In [ ]:
z = np.zeros((2,3))
z

In [ ]:
# zeros((1,2,3)) = ar1(ar2(ar3(),ar3()))
z1 = np.zeros((1,2,3))
z1

In [ ]:
a = np.ones((1,2) , dtype=int)
a

In [ ]:
a= np.ones((3,3))
a

In [ ]:
a = np.ones((2,2,2))
a

> Numpy Array Manipulation

In [ ]:
b = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]] , dtype=np.int8)
b

In [ ]:
#transpose of matrix in numpy
i = np.transpose(b)
i

In [ ]:
#shortcut of transpose of matrix or array
i.T

In [ ]:
#flattening array from nXnXn... to n
b = i.ravel()
b

In [ ]:
#it used array 1D array and size of 1D array = parameter given n ,m product(n*m)
b.reshape(9,1)


> Adding and removing elements from  array

In [ ]:
 b = b.reshape(3,3)
 b

In [ ]:
a = np.array([[1,2],[3,4]])
a.resize((3,5))
a

In [ ]:
b = np.append(b , np.array([10,20,30],dtype=np.int8))
b

In [ ]:
b = np.append(b , np.array([10,20,30],dtype=np.int8))
b

In [ ]:
b.size

In [ ]:
b.resize((5,3))
b

> Array Manipulation in 2 Dimension Array

In [ ]:
b = b[:4,:]
b

In [ ]:
#slicing columns of numpy array b
col1 = b[:,0]
col2 = b[:,1]
col3 = b[:,2]
col1 , col2 , col3

In [ ]:
#slicing rows in numpy array b
row1 = b[0,]
row2 = b[1,]
row3 = b[2,]
row1 , row2 , row3

In [ ]:
b[0,1] , b[0,2] , b[1,0] , b[1,2]

In [ ]:
b[0:2,] 

In [ ]:
b[:1]

In [ ]:
b[1,...]

In [ ]:
b

In [ ]:
#reversing array by slicing
b[: : -1] , b[: : -1]


In [ ]:
b[: -1 :]

In [ ]:
b[: : -2]

In [ ]:
b[: : -3]

In [ ]:
b[: : -4]

In [ ]:
b[: : -5]

In [ ]:
b[: : -6]

In [ ]:
b[: : -100]

In [ ]:
b[0:2,2]

> QUE : Create array like this
[[1,1,1],
[1,0,1],
[1,1,1]]
using numpy array slicing from this array 
[[1,2,3],
[4,5,6],
[7,8,9]]

In [ ]:
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
a

In [ ]:
for i in range(0 , a[0,...].size):
    a[0,...] = 1
    a[2,...] = 1
    a[...,0] = 1
    a[...,2] = 1
    


In [ ]:
a

In [ ]:
n = int(a[1,...].size/2)
a[n,n] = 0
a

In [ ]:
b

In [ ]:
c = b.ravel()
c

In [ ]:
c[c>5]

In [ ]:
c[c>=10]

In [ ]:
b[[1,0,2],[1,0,2]]

In [ ]:
b[[1,2,0,0,1,1,2,1,1,2],[1,2,0,0,1,1,2,1,1,2]]

In [ ]:
b.ctypes

In [ ]:
b.nbytes

## Numpy Operations

In [ ]:
a,b

In [ ]:
a.std()

In [ ]:
b.std()

In [ ]:
a.mean() , b.mean()

In [ ]:
a.sum() , b.sum()

In [ ]:
a.sum(axis=0), b.sum(axis=0) # it is row wise sum

In [ ]:
a.sum(axis=1), b.sum(axis=1) # it is column wise sum

In [ ]:
a.var() , b.var()

In [ ]:
a+10

In [ ]:
b*2

In [ ]:
b[0] *=2
b

In [ ]:
b

In [ ]:
a-10

In [ ]:
a+0

In [ ]:
# a and b are not of same size so we will make it same by slicing b
[i for i in b[:b[0,].size,]+a]

In [ ]:
n = np.array([[4,5,6,7],[7,8,9,10],[0,1,2,3]])
n

In [ ]:
n1 = np.array([[1,2,3],[5,6,7]])
n1

In [ ]:
n[:2,0:3]

In [ ]:
n[:2,0:3]+n1

In [ ]:
n[:2,:3], n[:2,1:], n[1:,:3]  , n[1:,1:4]

### Initial PlaceHolders or (Vectorizing and Broadcasting)

In [ ]:
np.zeros((2,2))#it will be float by default

In [ ]:
np.zeros((2,2,2) , dtype=int)

In [ ]:
np.ones((2,3)) #it will be float by default

In [ ]:
n = np.ones((3,3),dtype=int) #we can change data type from float to int
n[n[1].size-2,n[1].size-2] = 0
n

In [ ]:
d = np.arange(10,25,5)
#np.arange(start , end , gap of) like 2,4,6,4,8,10 her gap = 2,start=2 end = 11or12
d

In [ ]:
np.linspace(0,2,9)
# same as arange but will space between elements and by default=float
#we can even specify data type and 3rd parameter is total no. of element in array

In [ ]:
np.linspace(0,2,9 , dtype=int)

### Numpy Boolean Array 
>also called as masks

In [190]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [191]:
a+20

array([20, 21, 22, 23])

In [192]:
a[[0,-1]]

array([0, 3])

In [193]:
a[[True ,False,True ,False]]

array([0, 2])

In [194]:
a>=2

array([False, False,  True,  True])

In [195]:
a[a>=2]

array([2, 3])

In [199]:
a = np.append(a , np.array([i for i in range(5,10)]))
a

array([0, 1, 2, 3, 5, 6, 7, 8, 9, 5, 6, 7, 8, 9])

In [201]:
a[a>5]

array([6, 7, 8, 9, 6, 7, 8, 9])

In [202]:
a[a>a.mean()]

array([6, 7, 8, 9, 6, 7, 8, 9])

In [203]:
a[~(a>a.mean())]

array([0, 1, 2, 3, 5, 5])

In [206]:
a[(a<=2) | (a>1)]

array([0, 1, 2, 3, 5, 6, 7, 8, 9, 5, 6, 7, 8, 9])

In [207]:
a[(a<=2) & (a>1)]

array([2])

In [208]:
b = np.random.randint(100,size=(3,3)) #numpy inherits random ps in numpy we can use random just as wee use 
b

array([[97, 81, 99],
       [67, 19, 26],
       [39, 59, 59]])

In [209]:
b[b>b.mean()]

array([97, 81, 99, 67])

## Linear Algebra

In [214]:
a = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
b = np.random.randint(10,size=(3,2))

In [215]:
a,b

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[9, 0],
        [6, 4],
        [6, 1]]))

In [216]:
a.dot(b) # for multiplication of two matrices

array([[ 39,  11],
       [102,  26],
       [165,  41]])

In [218]:
a@b #shortcut for matrix multiplication

array([[ 39,  11],
       [102,  26],
       [165,  41]])

In [232]:
b = np.append(b,np.array([1,5,9]))

In [238]:
b = b[:9].reshape((3,3))
b

array([[9, 0, 6],
       [4, 6, 1],
       [1, 5, 9]])

In [239]:
a+b

array([[10,  2,  9],
       [ 8, 11,  7],
       [ 8, 13, 18]])

In [241]:
b.T # transpose shortcut

array([[9, 4, 1],
       [0, 6, 5],
       [6, 1, 9]])